class UserSerializer < ActiveModel::Serializer
  attributes :id,
              :email,
              :full_name,
              :first_name,
              :last_name,
              :encrypted_password,
              :reset_password_token,
              :reset_password_sent_at,
              :remember_created_at,
              :sign_in_count,
              :current_sign_in_at,
              :last_sign_in_at,
              :current_sign_in_ip,
              :last_sign_in_ip,
              :user_type,
              :country_id,
              :city_id,
              :continent_id,
              :phone,
              :date_of_birth
end
